-- Create tables and constraints

CREATE TABLE AUTO_MEMORY_DOLL 
    ( 
     id             NUMBER (5)  NOT NULL , 
     name           VARCHAR2 (100)  NOT NULL , 
     age            NUMBER (2)  NOT NULL , 
     DOLL_STATUS_id NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE AUTO_MEMORY_DOLL 
    ADD CONSTRAINT AutoMemoryDoll_PK PRIMARY KEY ( id ) ;

CREATE TABLE CLIENT 
    ( 
     id            NUMBER (6)  NOT NULL , 
     name          VARCHAR2 (100)  NOT NULL , 
     phone         NUMBER (11)  NOT NULL , 
     city          VARCHAR2 (50)  NOT NULL , 
     letter_reason VARCHAR2 (200)  NOT NULL , 
     email         VARCHAR2 (100)  NOT NULL , 
     address       VARCHAR2 (150)  NOT NULL 
    ) 
;

ALTER TABLE CLIENT 
    ADD CONSTRAINT Client_PK PRIMARY KEY ( id ) ;

CREATE TABLE DOLL_STATUS 
    ( 
     id     NUMBER (1)  NOT NULL , 
     status VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE DOLL_STATUS 
    ADD CONSTRAINT DollStatus_PK PRIMARY KEY ( id ) ;

CREATE TABLE LETTER 
    ( 
     id                  NUMBER (7)  NOT NULL , 
     "date"              DATE  NOT NULL , 
     content_summary     VARCHAR2 (200)  NOT NULL , 
     CLIENT_id           NUMBER (6)  NOT NULL , 
     AUTO_MEMORY_DOLL_id NUMBER (5)  NOT NULL , 
     LETTER_STATUS_id    NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE LETTER 
    ADD CONSTRAINT Letter_PK PRIMARY KEY ( id ) ;

CREATE TABLE LETTER_STATUS 
    ( 
     id     NUMBER (1)  NOT NULL , 
     status VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE LETTER_STATUS 
    ADD CONSTRAINT LetterStatus_PK PRIMARY KEY ( id ) ;

ALTER TABLE AUTO_MEMORY_DOLL 
    ADD CONSTRAINT AUTO_MEMORY_DOLL_STATUS_FK FOREIGN KEY 
    ( 
     DOLL_STATUS_id
    ) 
    REFERENCES DOLL_STATUS 
    ( 
     id
    ) 
;

ALTER TABLE LETTER 
    ADD CONSTRAINT LETTER_AUTO_MEMORY_DOLL_FK FOREIGN KEY 
    ( 
     AUTO_MEMORY_DOLL_id
    ) 
    REFERENCES AUTO_MEMORY_DOLL 
    ( 
     id
    ) 
;

ALTER TABLE LETTER 
    ADD CONSTRAINT LETTER_CLIENT_FK FOREIGN KEY 
    ( 
     CLIENT_id
    ) 
    REFERENCES CLIENT 
    ( 
     id
    ) 
;

ALTER TABLE LETTER 
    ADD CONSTRAINT LETTER_LETTER_STATUS_FK FOREIGN KEY 
    ( 
     LETTER_STATUS_id
    ) 
    REFERENCES LETTER_STATUS 
    ( 
     id
    ) 
;

-- Create sequences and triggers to automate the id creation of each row of
-- each table

CREATE SEQUENCE SEQ_AUTO_MEMORY_DOLL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_AUTO_MEMORY_DOLL_BI
BEFORE INSERT ON AUTO_MEMORY_DOLL
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT SEQ_AUTO_MEMORY_DOLL.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/


CREATE SEQUENCE SEQ_CLIENT
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENT_BI
BEFORE INSERT ON CLIENT
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT SEQ_CLIENT.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/


CREATE SEQUENCE SEQ_CLIENT
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENT_BI
BEFORE INSERT ON CLIENT
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT SEQ_CLIENT.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/


CREATE SEQUENCE SEQ_LETTER
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_LETTER_BI
BEFORE INSERT ON LETTER
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT SEQ_LETTER.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/


CREATE SEQUENCE SEQ_LETTER_STATUS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_LETTER_STATUS_BI
BEFORE INSERT ON LETTER_STATUS
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT SEQ_LETTER_STATUS.NEXTVAL INTO :NEW.id FROM dual;
  END IF;
END;
/

-- Test add client








